### ISSUE TITLE
dialog component

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#108]
We need a `<dialog>` component.

I guess it's first draft can be something like:

```scss
@use '../abstracts' as my;

dialog {
  position: fixed;
  top: 50%;
  z-index: my.layer('default');

  background-color: my.palette('white');
  border: 0;

  transform: translate(0, -50%);

  &::backdrop {

  }

  + .backdrop {

  }
}
```

And the selector `dialog[tabindex]` should be flagged as error.
