### ISSUE TITLE
Mixin for inner border

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#110]
Should we turn this into a mixin?

```scss
th + th,
td + th,
th + td,
td + td {
  border-left: my.$stroke__thin solid my.palette('neutral', 'dark');
}

tr + tr th,
tr + tr td {
  border-top: my.$stroke__thin solid my.palette('neutral', 'dark');
}
```

Would it make the next branch better, @Eduruiz ?
