### ISSUE TITLE
Inline-break mixin

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#125]
Add:

```scss
@mixin inline-break($position: 'before') {
    @if $position != 'before' and $position != 'after' {
        @error 'invalid position submited: #{$position}';
    }
    
  &::#{$position} {   
    white-space: pre;

    content: '\A';
  }
}
```
