### ISSUE TITLE
Inline-background mixin

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#126]
```scss
@mixin inline-background ($position-of-break: 'before') {
  display: inline;
  
  box-decoration-break: clone;

  @include inline-break($position-of-break) {
    margin-right: -2em;
    margin-left: -2em;

    font-family: monospace;
    color: transparent;
  }
}
```

depends on #125
