### ISSUE TITLE
Forbid `<a>` within `<label>`

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#127]
From [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content):

> [Interactive content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content)
>
> Don't place interactive elements such as [anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) or [buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) inside a label. Doing so makes it difficult for people to activate the form input associated with the label.

```scss
label a,
label button {
	@extend %warning;

	@include alert {
		content: 'do not place interactive elements such as `<anchors>` or `<buttons>` inside a label' !important;
	}
}
```
