### ISSUE TITLE
Convert italic into a mixin

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#132]
Since sometimes italic can be set as a different color or weight, it makes sense to set everything at once.

For example, the following:

```scss
@mixin italic {
  font-style: italic;
}
```

Can become:

```scss
@mixin italic {
  font-style: normal;
  font-weight: 100;
}
```
