### ISSUE TITLE
Improve disabled buttons styles

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#133]
Disabled buttons are harder for people with disabliities to use.

So, let's improve them using `aria-disabled`:

```scss
  &[aria-disabled='true'],
  &:disabled {
    cursor: not-allowed;

    filter: grayscale(100%);
  }
```
