### ISSUE TITLE
Add styles for label of required fields

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#134]
```scss

  &:has(+ :required)::after {
    color: my.palette('signage', 'danger');

    content: ' *';
  }
```
