### ISSUE TITLE
Prevent layout issue on the pseudo-element of loading state

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#140]
```scss
%loading-el {
  overflow: hidden;

  cursor: wait;

  &::after {
    // prevent conflicts
    all: unset;

    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: my.layer('modal');

    content: '';
  }
}
```
