### ISSUE TITLE
Check color of quotation marks

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#142]
Is this really right?

```scss
q,
blockquote {
	font-style: italic;

	color: palette('quotes');
}
```
