### ISSUE TITLE
Prevent focus indicator on script only focusable elements

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#15]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/15) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [sobral](https://github.com/sobral)).**

----------------------------------------

If the user can't focus, why should we represent it?

```css
[tabindex='-1'] {
  &:focus {
    outline: 0;
  }
}
```
