### ISSUE TITLE
Universal reset mixin

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#44]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/44) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

```scss
@mixin universal-reset {
  position: static;

  float: none;
  clear: none;

  width: auto;
  height: auto;
  max-width: none;
  max-height: none;
  min-width: 0;
  min-height: 0;

  padding: 0;
  margin: 0;

  font-size: 1em;
  line-height: 1;
  font-family: inherit;

  vertical-align: baseline;

  list-style: none;

  cursor: default;

  background-image: none;

  border: 0;
  border-radius: 0;

  quotes: none;

  outline: 0;

  border-collapse: collapse;
  border-spacing: 0;

&,
&:link,
&:visited,
&:hover,
&:focus,
&:focus-within,
&:active {
  font-style: normal;
  font-weight: normal;

  text-decoration: none;
  text-transform: none;

  background-color: transparent;

  box-shadow: none;
}

  &::before,
  &::after {
    content: none;
  }
}
```
