### ISSUE TITLE
input color isn't impossible anymore

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#47]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/47) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

Despite it needs a wrapper.

```scss
%inputColor {
  @extend %text-field-reset;

  cursor: pointer;

  background-color: palette('white'); /* 1 */

  appearance: none;
}

[type='color'] {
  @extend %inputColor;
}

.input-color__wrapper {
  @extend %inputColor;

  overflow: hidden;
}
```
