### ISSUE TITLE
Blink polyfill

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#58]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/58) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

```css
@keyframes condemned_blink_effect {
  0% {
    visibility: hidden;
  }
  50% {
    visibility: hidden;
  }
  100% {
    visibility: visible;
  }
}
```
