### ISSUE TITLE
Improve pseudo hamburguer icon

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#59]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/59) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

[https://timkadlec.com/2012/08/mobile-navigation-icons/](https://timkadlec.com/2012/08/mobile-navigation-icons/)

[https://gist.github.com/tkadlec/3091105](https://gist.github.com/tkadlec/3091105)

‌

```css
.border-menu {
  position: relative;
  padding-left: 1.25em;
}

.border-menu:before {
  content: "";
  position: absolute;
  top: 0.25em;
  left: 0;
  width: 1em;
  height: 0.125em;
  border-top: 0.375em double #000;
  border-bottom: 0.125em solid #000;
  box-sizing: content-box;
}
```

‌
