### ISSUE TITLE
Accessibility media rules

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#61]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/61) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

From [https://github.com/csstools/sanitize.css/issues/194](https://github.com/csstools/sanitize.css/issues/194)

```css
@media(prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    transition: none !important;
    animation: none !important;
    scroll-behavior: auto !important;
  }
}
```

‌
