### ISSUE TITLE
input type number

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#75]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/75) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

To remove little spin buttons.

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    /* display: none; <- Crashes Chrome on hover */
    -webkit-appearance: none;
    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
}

input[type=number] {
    -moz-appearance:textfield; /* Firefox */
}
```

‌
